# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](#FFFFFF)\
$time\
[î‚°](bg:black fg:white)\
$os\
$username\
[î‚°](bg:blue fg:black)\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$kotlin\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
$status\
[î‚°](fg:green)\
$character\
"""

[character]
success_symbol = "(purple)" #"\n\\$ (purple)"
error_symbol = "(red)"
vimcmd_symbol = "(green)"

[status]
style = 'bg:green fg:white'
symbol = 'âœ˜'
success_symbol = 'âœ“'
not_found_symbol = '?'
format = '[ $symbol$signal_name$maybe_int ]($style)'
map_symbol = true
disabled = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:black"
style_root = "bg:black fg:red"
format = '[ MRZ07 ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
format = 'ï£¿'
disabled = true      # Disabled by default

#[battery]
#full_symbol = 'ğŸ”‹ '
#charging_symbol = 'âš¡ï¸ '
#discharging_symbol = 'ğŸ’€ '

#[[battery.display]]
#threshold = 20
#style = 'bold red'
#discharging_symbol = 'ğŸ’€ '

#[[battery.display]]
#threshold = 50
#style = 'bg:#F7CC1C fg:black'
#discharging_symbol = 'âš¡ï¸ '

#[[battery.display]]
#threshold = 60
#style = 'bg:green fg:white'
#discharging_symbol = 'âš¡ï¸ '

[directory]
style = "bg:blue fg:white"   # #DA627D
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "../"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
symbol = "î˜ "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A fg:white"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'
disabled = true                           # Disabled by default

[elm]
symbol = "î˜¬ "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'
disabled = true                           # Disabled by default

[git_branch]
symbol = "ï˜"
style = "bg:yellow fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:yellow fg:black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'
disabled = true                           # Disabled by default

[java]
symbol = "î‰– "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'
disabled = true                           # Disabled by default

[nodejs]
symbol = "â¬¡"
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'
disabled = true                           # Disabled by default

[rust]
symbol = "î¨"
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#65AEF7 fg:white"
format = '[ $symbol ($version) ]($style)'
disabled = true                           # Disabled by default

[time]
disabled = false
time_format = "%T"
style = "bg:#FFFFFF fg:black"
format = '[$time ]($style)'
